name: release-to-maven-central

on:
  push:
    tags:
      - jdependency-*

jobs:
  ossrh:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    environment: maven-central
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Version
        uses: tcurdt/action-verify-version-maven@main

      - name: Setup Maven Central
        uses: actions/setup-java@v5
        with: # overwrite settings.xml
          distribution: "zulu"
          java-version: 21
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Publish to Maven Central
        run: mvn -B -Prelease --file pom.xml deploy
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

      - name: Extract release notes
        uses: ffurrer2/extract-release-notes@v3
        with:
          changelog_file: CHANGELOG.md
          release_notes_file: RELEASE_NOTES.md

      - name: Create GitHub release
        run: |
          # remove jdependency- prefix of the tag.
          release_name="${GITHUB_REF_NAME#jdependency-}"
          gh release create ${GITHUB_REF_NAME} --title $release_name --notes-file RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
